apiVersion: '2019-12-01'
location: northeurope
name: convmos-evaluate
properties:
  containers:
  - name: worker
    properties:
      environmentVariables: []
      image: steimi/sd-next:1.4.10
      resources:
        requests:
          cpu: 4.0
          memoryInGB: 16.0
      volumeMounts:
      - mountPath: "/workspace/results"
        name: results
      - mountPath: "/scratch"
        name: scratch
      command: ["python", "-u", "evaluate.py", "-r", "-p", "4", "--path-prefix", "/scratch/steininger/deepsd/convmos_paper_runs"]
  osType: Linux
  restartPolicy: Never
  volumes:
  - name: results
    azureFile:
      sharename: results
      storageAccountName: INSERT_YOUR_NAME
      storageAccountKey: INSERT_YOUR_KEY
  - name: scratch
    azureFile:
      sharename: scratch
      storageAccountName: INSERT_YOUR_NAME
      storageAccountKey: INSER_YOUR_KEY 
  imageRegistryCredentials: # Credentials to pull a private image
  - server: index.docker.io
    username: steimi
    password: ${DOCKER_HUB_PW}
tags: {}
type: Microsoft.ContainerInstance/containerGroups
